package edu.calstate.tmcp.model.queries;

import edu.calstate.tmcp.model.framework.TmcpViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 26 16:04:49 PST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TmcCsuPVImpl
  extends TmcpViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public TmcCsuPVImpl()
  {
  }
}

