package edu.calstate.tmcp.model.queries;

import edu.calstate.tmcp.model.framework.TmcpViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 28 18:29:42 PST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TmcCsuPViewImpl
  extends TmcpViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public TmcCsuPViewImpl()
  {
  }
}

