package edu.calstate.tmcp.model.queries;

import edu.calstate.tmcp.model.framework.TmcpViewRowImpl;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 28 18:29:40 PST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TmcCsuPViewRowImpl
  extends TmcpViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    CampusCode,
    DegreeType,
    DegreePrgCodeMajor,
    DegreePrgCodeOption,
    OptionSuffix,
    Source,
    TmcCode,
    CampusName,
    DegreePrgTitleMajor,
    DegreePrgTitleOption,
    CampusSpecMajorTitle,
    CampusSpecificOptionTitle,
    MajorTwo,
    DisciplineTitle,
    DeliveryFormat1,
    CipCode,
    TmcDescription,
    CccProgramType,
    Approved,
    ApprovedDate,
    EffectiveTerm,
    EffectiveDate,
    InactiveTerm,
    InactiveDate,
    UpdateUser,
    UpdateDate,
    CreateUser,
    CreateDate,
    MoKey,
    AllCampusView1,
    DegreeTypeView1,
    VwAllDegreeCodes1,
    VwAllDegreeCodes2,
    TmcV1,
    DisciplineV1;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int CAMPUSCODE = AttributesEnum.CampusCode.index();
  public static final int DEGREETYPE = AttributesEnum.DegreeType.index();
  public static final int DEGREEPRGCODEMAJOR = AttributesEnum.DegreePrgCodeMajor.index();
  public static final int DEGREEPRGCODEOPTION = AttributesEnum.DegreePrgCodeOption.index();
  public static final int OPTIONSUFFIX = AttributesEnum.OptionSuffix.index();
  public static final int SOURCE = AttributesEnum.Source.index();
  public static final int TMCCODE = AttributesEnum.TmcCode.index();
  public static final int CAMPUSNAME = AttributesEnum.CampusName.index();
  public static final int DEGREEPRGTITLEMAJOR = AttributesEnum.DegreePrgTitleMajor.index();
  public static final int DEGREEPRGTITLEOPTION = AttributesEnum.DegreePrgTitleOption.index();
  public static final int CAMPUSSPECMAJORTITLE = AttributesEnum.CampusSpecMajorTitle.index();
  public static final int CAMPUSSPECIFICOPTIONTITLE = AttributesEnum.CampusSpecificOptionTitle.index();
  public static final int MAJORTWO = AttributesEnum.MajorTwo.index();
  public static final int DISCIPLINETITLE = AttributesEnum.DisciplineTitle.index();
  public static final int DELIVERYFORMAT1 = AttributesEnum.DeliveryFormat1.index();
  public static final int CIPCODE = AttributesEnum.CipCode.index();
  public static final int TMCDESCRIPTION = AttributesEnum.TmcDescription.index();
  public static final int CCCPROGRAMTYPE = AttributesEnum.CccProgramType.index();
  public static final int APPROVED = AttributesEnum.Approved.index();
  public static final int APPROVEDDATE = AttributesEnum.ApprovedDate.index();
  public static final int EFFECTIVETERM = AttributesEnum.EffectiveTerm.index();
  public static final int EFFECTIVEDATE = AttributesEnum.EffectiveDate.index();
  public static final int INACTIVETERM = AttributesEnum.InactiveTerm.index();
  public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
  public static final int UPDATEUSER = AttributesEnum.UpdateUser.index();
  public static final int UPDATEDATE = AttributesEnum.UpdateDate.index();
  public static final int CREATEUSER = AttributesEnum.CreateUser.index();
  public static final int CREATEDATE = AttributesEnum.CreateDate.index();
  public static final int MOKEY = AttributesEnum.MoKey.index();
  public static final int ALLCAMPUSVIEW1 = AttributesEnum.AllCampusView1.index();
  public static final int DEGREETYPEVIEW1 = AttributesEnum.DegreeTypeView1.index();
  public static final int VWALLDEGREECODES1 = AttributesEnum.VwAllDegreeCodes1.index();
  public static final int VWALLDEGREECODES2 = AttributesEnum.VwAllDegreeCodes2.index();
  public static final int TMCV1 = AttributesEnum.TmcV1.index();
  public static final int DISCIPLINEV1 = AttributesEnum.DisciplineV1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public TmcCsuPViewRowImpl()
  {
  }
}

